"""
Game Theory Module
==================
RDMU Concept #2: Game Theory
Implements:
  1. Shapley Value — fair resource allocation based on marginal contribution
  2. Nash Equilibrium — stable strategy profile where no agent benefits by deviating
"""

import numpy as np
from math import factorial
from itertools import combinations, permutations
from typing import List, Dict, Callable, Tuple


def compute_shapley_values(agents: list,
                           total_resources: float,
                           disaster_severity: float) -> Dict[str, float]:
    """
    SHAPLEY VALUE COMPUTATION
    ─────────────────────────
    The Shapley value φᵢ gives each agent i their fair share of resources
    based on their marginal contribution to every possible coalition.

    Formula:
        φᵢ = Σ_{S⊆N\{i}} [|S|!(|N|-|S|-1)!/|N|!] * [v(S∪{i}) - v(S)]

    Where:
        N  = set of all agents
        S  = coalition not containing agent i
        v(S) = value (resource efficiency) generated by coalition S

    This ensures: Efficiency, Symmetry, Dummy Player, Additivity properties.
    """
    n = len(agents)
    shapley = {agent.name: 0.0 for agent in agents}

    # Define coalition value function v(S)
    # A coalition's value = pooled resources × synergy factor × severity multiplier
    def coalition_value(coalition_agents: list) -> float:
        if not coalition_agents:
            return 0.0
        pooled = sum(a.initial_resources for a in coalition_agents)
        # Synergy: cooperation among more agents yields increasing returns
        synergy = 1.0 + 0.15 * (len(coalition_agents) - 1)
        # Severity multiplier: more value generated under worse disasters
        severity_mult = 1.0 + disaster_severity * 0.3
        # Priority weighting: medical > rescue > logistics
        priority = np.mean([a.priority_weight for a in coalition_agents])
        return pooled * synergy * severity_mult * priority

    # Enumerate all permutations to compute exact Shapley values
    for agent in agents:
        marginal_sum = 0.0
        others = [a for a in agents if a.name != agent.name]

        # Sum over all subsets S of N \ {i}
        for r in range(len(others) + 1):
            for subset in combinations(others, r):
                subset_list = list(subset)
                # Weight = |S|! * (|N|-|S|-1)! / |N|!
                weight = (factorial(len(subset_list)) *
                          factorial(n - len(subset_list) - 1) /
                          factorial(n))
                # Marginal contribution = v(S ∪ {i}) - v(S)
                marginal = (coalition_value(subset_list + [agent]) -
                            coalition_value(subset_list))
                marginal_sum += weight * marginal

        shapley[agent.name] = marginal_sum

    # Normalize Shapley values to total available resources
    total_shapley = sum(shapley.values())
    if total_shapley > 0:
        shapley = {k: (v / total_shapley) * total_resources
                   for k, v in shapley.items()}
    else:
        equal = total_resources / n
        shapley = {agent.name: equal for agent in agents}

    return shapley


def find_nash_equilibrium(agents: list,
                          cooperation_incentive: float,
                          resource_scarcity: float) -> Dict[str, str]:
    """
    NASH EQUILIBRIUM FINDER
    ───────────────────────
    A Nash Equilibrium is a strategy profile where no agent can improve
    their payoff by unilaterally changing their strategy.

    We use a best-response iteration:
        1. Start with all agents cooperating
        2. Each agent checks: "Given others' strategies, is my strategy optimal?"
        3. Repeat until no agent wants to deviate
        4. Convergence = Nash Equilibrium

    Returns the stable strategy for each agent.
    """
    # Payoff matrix: (my_strategy, others_avg_strategy) → my payoff
    def individual_payoff(my_strategy: str,
                          others_cooperating_fraction: float,
                          agent) -> float:
        """Compute expected payoff for an agent given others' strategies."""
        if my_strategy == 'cooperate':
            # Cooperation is more valuable when others cooperate too (complementarity)
            payoff = (0.6 + others_cooperating_fraction * 0.4) * cooperation_incentive
            payoff += (1 - resource_scarcity) * 0.3  # Less scarcity → more value
        else:  # compete
            # Competition payoff: grab resources, but diminishes if others also compete
            payoff = 0.8 * (1 - others_cooperating_fraction * 0.5)
            payoff += resource_scarcity * 0.4  # More scarcity → more temptation
        return payoff * agent.risk_tolerance if my_strategy == 'compete' else payoff

    # Best-response iteration
    strategies = {agent.name: 'cooperate' for agent in agents}
    MAX_ITERATIONS = 50

    for _ in range(MAX_ITERATIONS):
        changed = False
        for agent in agents:
            others = [a for a in agents if a.name != agent.name]
            frac_others_coop = (
                sum(1 for a in others if strategies[a.name] == 'cooperate') /
                max(len(others), 1)
            )
            payoff_coop = individual_payoff('cooperate', frac_others_coop, agent)
            payoff_comp = individual_payoff('compete', frac_others_coop, agent)

            best = 'cooperate' if payoff_coop >= payoff_comp else 'compete'
            if best != strategies[agent.name]:
                strategies[agent.name] = best
                changed = True

        if not changed:  # Equilibrium reached
            break

    return strategies


def compute_fairness_index(allocations: Dict[str, float]) -> float:
    """
    JAIN'S FAIRNESS INDEX
    ─────────────────────
    F = (Σxᵢ)² / (n * Σxᵢ²)
    Range: [1/n, 1], where 1 = perfectly fair
    """
    values = list(allocations.values())
    n = len(values)
    if n == 0 or sum(values) == 0:
        return 0.0
    numerator = sum(values) ** 2
    denominator = n * sum(v ** 2 for v in values)
    return numerator / denominator if denominator > 0 else 0.0


def compute_social_welfare(payoffs: Dict[str, float],
                           strategies: Dict[str, str]) -> float:
    """
    Total social welfare = sum of all agent payoffs.
    Cooperation bonus: cooperative equilibria generate more total value.
    """
    base = sum(payoffs.values())
    coop_fraction = sum(1 for s in strategies.values() if s == 'cooperate') / len(strategies)
    return base * (1 + coop_fraction * 0.2)
