"""
Monte Carlo Simulation Engine
==============================
RDMU Concept #3: Monte Carlo Simulation
Models uncertainty in disaster response by running N stochastic trials.

Key uncertain variables modeled:
  - Actual disaster severity (varies from declared level)
  - Resource delivery reliability (logistics failures)
  - Agency response time (depends on route, availability)
  - Secondary disaster events (aftershocks, flooding spread)
"""

import numpy as np
import pandas as pd
from typing import List, Dict, Tuple
from dataclasses import dataclass


@dataclass
class TrialScenario:
    """One stochastic scenario generated by Monte Carlo sampling."""
    trial_id: int
    actual_severity: float       # Realized severity (uncertain around declared)
    resource_availability: float # Fraction of resources actually reachable
    agency_response_times: Dict[str, float]  # Minutes per agency
    secondary_event_prob: float  # P(cascading disaster)
    coordination_friction: float # Random communication delays


def generate_mc_scenarios(declared_severity: float,
                          base_resources: float,
                          n_trials: int = 1000,
                          seed: int = 42) -> List[TrialScenario]:
    """
    MONTE CARLO SCENARIO GENERATION
    ────────────────────────────────
    For each trial, sample uncertain parameters from distributions:

    - Severity:          Beta(α, β) — bounded [0,1], skewed by declared level
    - Resources:         Truncated Normal — around declared, with std = 15%
    - Response Times:    Log-Normal — right-skewed (mostly fast, some very slow)
    - Secondary Events:  Bernoulli — P increases with severity
    - Friction:          Uniform — random coordination delays

    Using N=1000 trials ensures stable mean/variance estimates (CLT).
    """
    rng = np.random.default_rng(seed)
    scenarios = []

    for i in range(n_trials):
        # --- Severity uncertainty (Beta distribution, bounded [0,1]) ---
        a = declared_severity * 8 + 1  # Shape param from declared severity
        b = (1 - declared_severity) * 8 + 1
        actual_sev = rng.beta(a, b)

        # --- Resource availability (truncated normal around declared) ---
        raw_res = rng.normal(loc=base_resources, scale=base_resources * 0.15)
        res_avail = np.clip(raw_res / base_resources, 0.4, 1.2)

        # --- Agency response times (Log-normal: mean 30-60 min) ---
        base_times = {'Medical Agency': 35, 'Rescue Agency': 45, 'Logistics Agency': 55}
        response_times = {}
        for agency, base_t in base_times.items():
            # Log-normal with mean=base_t, std≈30% of mean
            mu = np.log(base_t) - 0.5 * np.log(1 + 0.09)
            sigma = np.sqrt(np.log(1 + 0.09))
            response_times[agency] = rng.lognormal(mu, sigma)

        # --- Secondary event probability ---
        sec_prob = min(0.95, actual_sev * 0.6 + rng.uniform(0, 0.2))

        # --- Coordination friction (uniform random delay factor) ---
        friction = rng.uniform(0.8, 1.3)  # 1.0 = no friction

        scenarios.append(TrialScenario(
            trial_id=i,
            actual_severity=actual_sev,
            resource_availability=res_avail,
            agency_response_times=response_times,
            secondary_event_prob=sec_prob,
            coordination_friction=friction
        ))

    return scenarios


def compute_mc_statistics(results: List[Dict]) -> Dict:
    """
    Aggregate Monte Carlo results across all trials.
    Returns mean, std, 5th, 95th percentiles (confidence intervals).
    """
    if not results:
        return {}

    df = pd.DataFrame(results)
    stats = {}

    for col in df.select_dtypes(include=[np.number]).columns:
        stats[col] = {
            'mean': df[col].mean(),
            'std': df[col].std(),
            'p5': df[col].quantile(0.05),
            'p25': df[col].quantile(0.25),
            'median': df[col].median(),
            'p75': df[col].quantile(0.75),
            'p95': df[col].quantile(0.95)
        }

    return stats


def compute_value_at_risk(payoffs: List[float],
                          confidence: float = 0.95) -> Tuple[float, float]:
    """
    Value at Risk (VaR) — adapted for disaster response.
    Returns the worst-case payoff at the given confidence level,
    and Expected Shortfall (CVaR) — average of worst outcomes.
    """
    sorted_p = sorted(payoffs)
    var_idx = int((1 - confidence) * len(sorted_p))
    var = sorted_p[var_idx] if sorted_p else 0.0
    cvar = np.mean(sorted_p[:max(var_idx, 1)]) if sorted_p else 0.0
    return var, cvar
